name: "EEA - WWW"
description: "EEA website"
version: "10.2-rancher1"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
