.catalog:
  name: Logcentral Logspout
  version: 0.2.0-1
  description: |
    Logspout is a log router for Docker containers.
  questions:
    - variable: "route_uri"
      label: "Logspout route for logs"
      type: "string"
      required: true
      default: "syslog://logs.apps.eea.europa.eu:1514"
      description: |
        This will be the target where all logs are sent.
    - variable: "format"
      label: "Format"
      type: "enum"
      options:
        - "rfc5424"
        - "rfc3164"
      required: true
      default: "rfc5424"
      description: |
        The Syslog format to use.  If not certain, use rfc5424
