.catalog:
  name: "acme-full-stack"
  version: "v1.8-rancher1"
  description: "ACME full stack"
  uuid: acme-full-stack-7
  questions:
    - variable: "ui_port"
      description: "UI port"
      label: "Port:"
      required: true
      default: "1003"
      type: "int"
version: '2'
services:
  mongo:
    scale: 1
    start_on_create: true
  b2b:
    scale: 1
    start_on_create: true
  front-door:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: b2b-ui
        source_port: ${ui_port}
        target_port: 4000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true
  configservice:
    start_on_create: true
