name: "EEA - External"
description: "Easily create IP based external services"
version: "1.0-rancher1"
category: "External Services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
