version: "2"
catalog:
  name: "EEA - PostgreSQL"
  description: "PostgreSQL with DB init support"
  version: "9.6-rancher1"
  uuid: "www-postgres-2"
  minimum_rancher_version: "v1.2.0"
  upgrade_from: "9.6-rancher0"
  questions:
  - variable: "POSTGRES_HOST_LABELS"
    label: "Schedule services on hosts with the following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling services"
    default: "db=yes"
    type: "string"
    required: true
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTGRES_USER"
    label: "User name"
    description: "PostgreSQL super user name"
    default: "postgres"
    type: "string"
    required: true
  - variable: "POSTGRES_PASSWORD"
    label: "User password"
    description: "PostgreSQL super user password"
    default: "postgres"
    type: "password"
    required: true
  - variable: "POSTGRES_DBUSER"
    label: "DB user name"
    description: "PostgreSQL databases owner name"
    default: "zope"
    type: "string"
    required: true
  - variable: "POSTGRES_DBPASS"
    label: "DB user password"
    description: "PostgreSQL databases owner password"
    default: "zope"
    type: "password"
    required: true
  - variable: "POSTGRES_DBNAME"
    label: "DB names"
    description: "Space separated databases names to create on first run"
    default: "datafs zasync"
    type: "string"
    required: true
  - variable: "POSTGRES_REPLICATION_NETWORK"
    label: "Replication network"
    description: "Restrict replication only on this network (e.g.: 172.168.0.0/16)"
    default: ""
    type: "string"
  - variable: "DATA_VOLUME_DRIVER"
    label: "Data volume driver"
    description: "Volume driver for PostgreSQL data"
    default: "local"
    type: "enum"
    options:
    - "local"
    - "rancher-nfs"
    required: true
  - variable: "DATA_VOLUME_EXTERNAL"
    label: "Data volume environment scoped (external)"
    description: "DB Volume is environment scoped (externally created by other stack, e.g.: EEA WWW - Volumes)"
    default: "no"
    type: "enum"
    required: true
    options:
    - "yes"
    - "no"
  - variable: "DUMP_VOLUME_DRIVER"
    label: "Backup volume driver"
    description: "Volume driver for PostgreSQL backups"
    default: "local"
    type: "enum"
    options:
    - "local"
    - "rancher-nfs"
    required: true
  - variable: "DUMP_VOLUME_EXTERNAL"
    label: "Backup volume environment scoped (external)"
    description: "Backup volume is environment scoped (externally created by other stack, e.g.: EEA WWW - Volumes)"
    default: "no"
    type: "enum"
    required: true
    options:
    - "yes"
    - "no"
  - variable: "ARCHIVE_VOLUME_DRIVER"
    label: "WAL archive volume driver"
    description: "Volume driver for PostgreSQL WAL archive"
    default: "local"
    type: "enum"
    options:
    - "local"
    - "rancher-nfs"
    required: true
  - variable: "ARCHIVE_VOLUME_EXTERNAL"
    label: "Archive volume environment scoped (external)"
    description: "Archive volume is environment scoped (externally created by other stack, e.g.: EEA WWW - Volumes)"
    default: "no"
    type: "enum"
    required: true
    options:
    - "yes"
    - "no"
  - variable: "POSTGRES_CONFIG"
    label: "PostgreSQL config"
    description: "Multiline additional PostgreSQL configuration"
    type: "multiline"
    default: |-
      max_connections = 150
      wal_level = 'archive'
      archive_mode = 'on'
      archive_command = 'cp %p /var/lib/postgresql/archive/%f'
  - variable: "POSTGRES_CRONS"
    label: "Maintenance cron jobs"
    description: "Line separated list of cron jobs (e.g. Backup DB @nightly, Cleanup archive WALs @hourly, etc.). Use `crontab` syntax"
    type: "multiline"
    default: |-
      # Backup datafs DB daily at midnight
      @daily postgres /postgresql.restore/database-backup.sh datafs

services:
  master:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
